### ISSUE TITLE
Keyboard Macro REC

### ISSUE THREAD

**Issue by graph-kgrondin** [rivafarabi/deckboard#8]
It is possible to allow us to rec mutiple key, like ALT+092.

Actually, we can't, but i can do this by manually tap : ALT+NUMPAD_0+NUMPAD_9+NUMPAD_2

P.S : Great job on this app!

**Comment by rivafarabi** [comment]
Fixed in version 1.0.5

**Comment by graph-kgrondin** [comment]
Still not working in 1.2.0. When i try to REC **Alt+092**, it shows me **ALT+NUMPAD_2\** instead of **ALT+NUMPAD_0+NUMPAD_9+NUMPAD_2**
