### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GAMINGCHATS** [rivafarabi/deckboard#951]
When I install the Discord Extension it says it needs an update and when I click update to "Version" it doesn't update

https://user-images.githubusercontent.com/90594728/210058881-e76f91db-80d5-4b5c-9bde-fd26c0f2a77f.mp4

**Comment by osmancitci** [comment]
Fixed.

**Comment by GAMINGCHATS** [comment]
In version 2.1.4 it isn't fixed, and the Beta 3 doesn't have a plugin that I want.
